name: Build Java Injector DLL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build DLL with CL
      run: |
        # Visual Studio derleyici araçlarını aktif ediyoruz
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        
        # JNI yollarını ekleyerek tüm .cpp dosyalarını hile.dll olarak derliyoruz
        cl.exe /LD /I"%JAVA_HOME%\include" /I"%JAVA_HOME%\include\win32" *.cpp /Fe:hile.dll /EHsc
      shell: cmd

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: injector-dll-x64
        path: hile.dll
        
